// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIGMoObgso0mzHqm9P3i2i2BUuEJKHrQI',
    appId: '1:1085786149065:web:037743a6e2cea018cf7d18',
    messagingSenderId: '1085786149065',
    projectId: 'weatherapp-0101',
    authDomain: 'weatherapp-0101.firebaseapp.com',
    storageBucket: 'weatherapp-0101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WVtajZsmH3w3zwvCoziWzKhJ7x0shHY',
    appId: '1:1085786149065:android:35d02e3c84ebdf73cf7d18',
    messagingSenderId: '1085786149065',
    projectId: 'weatherapp-0101',
    storageBucket: 'weatherapp-0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqk2JdGP9oZB4C0ivuRnCawAqHhaFuio',
    appId: '1:1085786149065:ios:8439dff162bfb493cf7d18',
    messagingSenderId: '1085786149065',
    projectId: 'weatherapp-0101',
    storageBucket: 'weatherapp-0101.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqk2JdGP9oZB4C0ivuRnCawAqHhaFuio',
    appId: '1:1085786149065:ios:8439dff162bfb493cf7d18',
    messagingSenderId: '1085786149065',
    projectId: 'weatherapp-0101',
    storageBucket: 'weatherapp-0101.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIGMoObgso0mzHqm9P3i2i2BUuEJKHrQI',
    appId: '1:1085786149065:web:8e3116e015b8a5f8cf7d18',
    messagingSenderId: '1085786149065',
    projectId: 'weatherapp-0101',
    authDomain: 'weatherapp-0101.firebaseapp.com',
    storageBucket: 'weatherapp-0101.firebasestorage.app',
  );
}
